# Microsoft Graph PowerShell AutoRest Configuration
powershell: true
version: latest
use: "@autorest/powershell@latest"
module-version: 0.1.0
subject-prefix: ""
license-header: © Microsoft Corporation. All rights reserved.
azure: false
module-name: $(ModuleNamespace).$(title)
namespace: Microsoft.Graph.PowerShell
input-file: $(DocOutputFolder)\$(title).yml
output-folder: ..\src\$(GraphVersion)\$(title)\$(title)
clear-output-folder: true
use-internal-constructors: true
use-datetimeoffset : true
#sanitize-names: true
metadata:
  authors: Microsoft
  description: Microsoft Graph PowerShell module
  companyName: Microsoft
  owners: Microsoft
  requireLicenseAcceptance: true
  copyright: © Microsoft Corporation. All rights reserved.
  licenseUri: https://aka.ms/devservicesagreement
  projectUri: https://github.com/microsoftgraph/msgraph-sdk-powershell
  iconUri: https://raw.githubusercontent.com/microsoftgraph/g-raph/master/g-raph.png
  tags: Microsoft;Office365;Graph;PowerShell;GraphServiceClient;Outlook;OneDrive;AzureAD;GraphAPI;Productivity;SharePoint;Intune;SDK;
directive:
  - no-inline: # tells it not to inline the model with that name 
    - microsoft.graph.sharepointIds
    - microsoft.graph.identitySet
    - microsoft.graph.itemReference
    - microsoft.graph.directoryObject
    - microsoft.graph.user
    - microsoft.graph.drive
    - microsoft.graph.listItem
    - microsoft.graph.post
    - microsoft.graph.sectionGroup
    - microsoft.graph.team
# Modify OpenAPI doc - Add suffix 'fn' to Sites.Functions cmdlets to avoid duplicates.
  - from: Sites.Functions.yml
    where: $.paths.*
    transform: $.get.operationId = `${$.get.operationId}Fn`
# GroupMemberOf (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupMember
      variant: Get1
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: List
    set:
      subject: GroupMemberOf
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity1
    set:
      subject: GroupMemberOf
# GroupMemberWithLicenseError (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupMember
      variant: Get
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: List2
    set:
      subject: GroupMemberWithLicenseError
  - where:
      verb: Get
      subject: GroupMember
      variant: GetViaIdentity
    set:
      subject: GroupMemberWithLicenseError
# GroupTransitiveMemberOf (Groups.DirectoryObject)
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: List
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: Get
    set:
      subject: GroupTransitiveMemberOf
  - where:
      verb: Get
      subject: GroupTransitiveMember
      variant: GetViaIdentity
    set:
      subject: GroupTransitiveMemberOf
# RemoveSite (Sites.Actions)
  - where:
      verb: Remove
      subject: Site
      variant: Remove
    hide: true
  - where:
      verb: Remove
      subject: Site
      variant: RemoveExpanded
    hide: true
# GetSite (Sites.Site)
  - where:
      verb: Get
      subject: Site
      variant: Get1
    set:
      subject: SubSite
  - where:
      verb: Get
      subject: Site
      variant: List1
    set:
      subject: SubSite
  - where:
      verb: Get
      subject: Site
      variant: GetViaIdentity1
    set:
      subject: SubSite
# NewSite (Sites.Site)
  - where:
      verb: New
      subject: Site
      variant: Create1
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateExpanded1
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateViaIdentity
    set:
      subject: SubSite
  - where:
      verb: New
      subject: Site
      variant: CreateViaIdentityExpanded
    set:
      subject: SubSite
# GetReportTenantSecureScore (Reports)
  - where:
      verb: Get
      subject: ReportTenantSecureScore
      variant: GetViaIdentity
    remove: true
# Rename all delta cmdlets
  - where:
      verb: Invoke
      subject: (^Delta)(.*)
    set:
      verb: Get
      subject: $2$1